### PR TITLE
Fix all deprecations

### LINKED ISSUE #183: Fix all deprecations
Should fix use of all deprecated methods whether those are external or internal. Especially we should not deprecate something internally and then not do anything about it.

### PR DESCRIPTION
**Pull request by chrisjs**
Fixes #183

### CODE REVIEW

File: src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesDeployerProperties.java [hunk 1]
```diff
@@ -375,31 +360,31 @@ public void setStatefulSet(
 	 */
 	@Deprecated
```
Comment (viniciusccarvalho) [inline src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesDeployerProperties.java]: add `@deprecated Use {@link #getLimits()}` much like the one in `getCpu`?

Comment (chrisjs) [reply src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesDeployerProperties.java]: yes its there already
